# Generated by Django 2.2.5 on 2020-03-30 20:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('buildingID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buildingName', models.CharField(max_length=256)),
                ('buildingLocation', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('hours', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CRN',
            fields=[
                ('crnID', models.IntegerField(primary_key=True, serialize=False)),
                ('enrollmentNumber', models.IntegerField()),
                ('subject', models.CharField(max_length=4)),
                ('number', models.IntegerField()),
                ('buildingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=256)),
                ('productType', models.CharField(choices=[('DR', 'DRINK'), ('FO', 'FOOD')], default='FO', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loginName', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='VendingMachine',
            fields=[
                ('vmID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('VM_Location', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('WO', 'WORKING'), ('MA', 'MAINTENANCE'), ('DO', 'DOWN')], default='WO', max_length=2)),
                ('type', models.CharField(choices=[('DR', 'DRINK'), ('FO', 'FOOD')], default='FO', max_length=2)),
                ('buildingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crnID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.CRN')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.User')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Product')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.User')),
            ],
        ),
        migrations.CreateModel(
            name='Includes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Product')),
                ('vmID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.VendingMachine')),
            ],
        ),
    ]
