# Generated by Django 2.2.5 on 2020-03-30 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='hours',
        ),
    ]
