# Generated by Django 3.0.5 on 2020-04-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_auto_20200407_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userID',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, default='user', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
